name: CI

on:
  # pull_request:
  #   branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      casks:
        description: Custom list of casks to livecheck and bump if outdated
        required: false
  schedule:
    # run every 12 hours
    # - cron: "20 */12 * * *"
    # Every day at 5am
    - cron: "0 5 * * *"

env:
  HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
  HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
  HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}

  # FORMULAE: >
  CASKS: >
    pixel-perfect

permissions:
  contents: read

jobs:
  job1:
    name: Test Casks
    if: github.repository == 'ktnjared/homebrew-ktnjared'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ktnjared/homebrew-ktnjared
          ref: main
          path: homebrew-jared

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true
          cask: true
          test-bot: false

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Add Tap
        run: |
          brew tap ktnjared/ktnjared

      - name: Bump formulae
        uses: Homebrew/actions/bump-packages@master
        continue-on-error: true
        with:
          token: ${{ env.HOMEBREW_GITHUB_API_TOKEN }}
          formulae: ${{ env.FORMULAE }}

      - name: Bump casks
        uses: Homebrew/actions/bump-packages@master
        continue-on-error: true
        with:
          token: ${{ env.HOMEBREW_GITHUB_API_TOKEN }}
          casks: ${{ github.event.inputs.casks || env.CASKS }}
